name: prices_and_labels

packages:
  - .
  - packages/**

scripts:
  analyze:
    exec: dart analyze .

  get:
    run: flutter pub get
    exec:
      concurrency: 1
    description: flutter pub get
  upgrade:
    run: flutter pub upgrade --major-versions
    exec:
      concurrency: 1
    description: flutter pub upgrade

  build:build_runner:
    exec: dart run build_runner build --delete-conflicting-outputs
    description: dart run build_runner build --delete-conflicting-outputs
