on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

name: Build android prod
jobs:
  build-aab:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install java
        uses: actions/setup-java@v3
        with:
          java-version: "17.0.1"
          distribution: "oracle"

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Service account key
        run: echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties

      - name: Build aab
        run: flutter build appbundle --release

      - uses: actions/upload-artifact@v4
        id: upload-aab
        with:
          name: app-release.aab
          path: build/app/outputs/bundle/release/app-${{inputs.version}}.aab

  upload-to-appstore:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-aab
    steps:
      - uses: actions/checkout@v3

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          working-directory: "android"
          bundler-cache: true

      - name: Play store credentials
        run: echo "${{vars.PLAY_STORE_UPLOAD_KEY}}" | base64 -d > android/fastlane/play-store-credentials.json

      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: app-${{inputs.version}}.aab
          path: build/app/outputs/bundle/release

      - name: Deploy to playstore
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: "uploadToPlayStore"
          subdirectory: "android"
