name: authentication_repository
resolution: workspace
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: "none"

environment:
  sdk: ">=3.7.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  cache: 1.0.0
  equatable: ^2.0.5
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  google_sign_in: ^6.2.1
  logger: ^2.3.0
  meta: ^1.12.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
