// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-IyDkqY-986sqkiDcjrb4M0Voa0omPns',
    appId: '1:779293068741:web:b47b6fd4416d7b800dcfac',
    messagingSenderId: '779293068741',
    projectId: 'dayder-d7398',
    authDomain: 'dayder-d7398.firebaseapp.com',
    storageBucket: 'dayder-d7398.appspot.com',
    measurementId: 'G-JJYSPP19ZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRFh7k8dZSkX3VVOZDmoJoMhfJeiAnxwk',
    appId: '1:779293068741:android:392276c12eac8cc20dcfac',
    messagingSenderId: '779293068741',
    projectId: 'dayder-d7398',
    storageBucket: 'dayder-d7398.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqJIQA_5YD0bYrw01fb0Ef6y157y75gcM',
    appId: '1:779293068741:ios:e2ee902212a9419b0dcfac',
    messagingSenderId: '779293068741',
    projectId: 'dayder-d7398',
    storageBucket: 'dayder-d7398.appspot.com',
    androidClientId: '779293068741-ksc836qkufe7pajlf979mk1k2ibi1h1o.apps.googleusercontent.com',
    iosClientId: '779293068741-05ou5p1rcka6mveo560jhmp94t5s1avb.apps.googleusercontent.com',
    iosBundleId: 'com.dayder.application.dayder',
  );

}