name: remote_config_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  cache:
    path: ../cache
  firebase_analytics: ^11.1.0
  firebase_core: ^3.1.0
  firebase_remote_config: ^5.0.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
