# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
    desc "Upload to appDistrib"
    lane :uploadToAppDistrib do
        firebase_app_distribution(
            app: ENV["FIREBASE_APP_ID_ANDROID"],
            service_credentials_file: "fastlane/service-account-key.json",
            groups: "testers",
            release_notes: "Lots of amazing new features to test out!",
            android_artifact_path:"../build/app/outputs/apk/debug/app-debug.apk",
            android_artifact_type:"APK",
        )
    end

    desc "Upload to playstore"
    lane :uploadToPlayStore do
        androidRelease
        upload_to_play_store(
            json_key: "fastlane/play-store-credentials.json",
            aab: "../build/app/outputs/bundle/release/app-release.aab",
            release_status:"draft"
        )
    end
end
