# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build app bundle release"
  lane :beta do
    gradle(
        task: 'assemble',
        build_type: 'Release'
         properties: {
            "android.injected.signing.store.file" => "keystore.jks",
            "android.injected.signing.store.password" => ENV["ANDROID_STORE_PASSWORD"],
            "android.injected.signing.key.alias" => ENV["ANDROID_KEY_ALIAS"],
            "android.injected.signing.key.password" => ENV["ANDROID_STORE_PASSWORD"],
         }
    )
  end

  desc "Upload to playstore"
  lane :deploy do
    upload_to_play_store(
      json_key: "fastlane/play-store-credentials.json",
    )
  end
end
