# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build app bundle release"
  lane :beta do
    sh('pwd')
    gradle(
          task: 'build',
          build_type: 'Release',
       )
  end

  desc "validate play store key"
  lane :deploy do
    upload_to_play_store(
      json_key: "fastlane/play-store-credentials.json",
    )
  end
end
