on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      KEY_PROPERTIES:
        required: true
      SA_FIREBASE:
        required: true
      FIREBASE_APP_ID_ANDROID:
        required: true
      FIREBASE_OPTIONS:
        required: true
      GOOGLE_SERVICES:
        required: true

name: Build
jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Write Google Services
        run: echo "${{ secrets.GOOGLE_SERVICES }}" | base64 -d > android/app/google-services.json

      - name: Write Service account key
        run: echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties

      - name: Write Firebase options
        run: echo "${{secrets.FIREBASE_OPTIONS}}" > lib/firebase_options.dart

      - name: Flutter get
        run: flutter pub get

      - name: Build apk
        run: flutter build apk --debug

      - name: Rename apk
        run: mv build/app/outputs/apk/debug/app-debug.apk build/app/outputs/apk/debug/app-${{inputs.version}}.apk

      - uses: actions/upload-artifact@v4
        id: upload-apk
        with:
          name: app-${{inputs.version}}.apk
          path: build/app/outputs/apk/debug/

  build-ios:
    name: Build ios
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: build ios
        run: echo "Build ios"
