on:
  push:
    branches:
      - develop
name: Build android debug
jobs:
  build-apk:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install java
        uses: actions/setup-java@v3
        with:
          java-version: "17.0.1"
          distribution: "oracle"

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Service account key
        run: echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties

      - name: Build apk
        run: flutter build apk --debug

      - uses: actions/upload-artifact@v4
        id: upload-apk
        with:
          name: app-debug.apk
          path: build/app/outputs/apk/debug/app-debug.apk

  upload-to-app-distrib:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-apk
    steps:
      - uses: actions/checkout@v3
      - run: echo "VERSION=`cat pubspec.yaml | grep -o 'version:[^:]*' | cut -f2 -d":" | xargs`" >> "$GITHUB_ENV"
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          working-directory: "android"
          bundler-cache: true

      - name: Service account key
        run: echo "${{ secrets.SA_FIREBASE }}" | base64 -d > android/fastlane/service-account-key.json

      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: app-debug.apk
          path: build/app/outputs/apk/debug

      - name: Rename apk
        run: mv build/app/outputs/apk/debug/app-debug.apk build/app/outputs/apk/debug/app-${{env.VERSION}}.apk

      - name: Deploy to app distrib
        uses: maierj/fastlane-action@v3.0.0
        env:
          FIREBASE_APP_ID_ANDROID: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
          ANDROID_ARTIFACT_PATH: "../build/app/outputs/apk/debug/app-${{env.VERSION}}.apk"
        with:
          lane: "uploadToAppDistrib"
          subdirectory: "android"
