name: Create Tag

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Create Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "Robot"
          git config user.email "robot@alphasow.dev"

      - name: App version
        run: echo "VERSION=`cat pubspec.yaml | grep -o 'version:[^:]*' | cut -f2 -d":" | cut -d"+" -f1 | xargs`" >> "$GITHUB_ENV"

      - name: New Tag
        run: |
          git tag -a $VERSION -m "Release version $VERSION"
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
