name: Prod

on:
  push:
    branches:
      - main

jobs:
  create-release:
    name: create release
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.semantic-release.outputs.new_release_version }}
    steps:
      - uses: actions/checkout@v4

      - name: Set GITHUB config
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"

      - name: 📝 Semantic release
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_android_prod:
    name: Android-prod
    needs: create-release
    uses: ./.github/workflows/build-prod.yaml
    with:
      version: ${{needs.create-release.outputs.release_version}}
    secrets:
      KEY_PROPERTIES: ${{secrets.KEY_PROPERTIES}}
      FIREBASE_OPTIONS: ${{secrets.FIREBASE_OPTIONS}}
      GOOGLE_SERVICES: ${{secrets.GOOGLE_SERVICES}}

  github_release:
    name: Create GitHub Release
    needs: [create-release, build_android_prod]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "Robot"
          git config user.email "robot@alphasow.dev"

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ needs.create-release.outputs.release_version }} --title ${{ needs.create-release.outputs.release_version }} --generate-notes
