on:
  push:
    branches:
      - "feature/*"
      - "fix/*"
      - "release/*"
      - "chore/*"

name: Test coverage
env:
  SC_VERSION: 5.0.1.3006
jobs:
  test-coverage:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sonar file
        run: echo "${{ secrets.SONAR_PROJECT_FILE }}" > sonar-project.properties

      - name: Install sonar-scanner
        run: |
          wget --output-document=sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SC_VERSION-linux.zip
          unzip sonar-scanner.zip
          echo "sonar-scanner-$SC_VERSION-linux/bin" >> $GITHUB_PATH

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Get dependencies
        run: flutter pub get

      - name: Flutter test
        run: flutter test --machine --coverage > tests.output

      - run: sonar-scanner

  details:
    name: Details
    needs: [test-coverage]
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{steps.app_version.outputs.new_version}}
    steps:
      - uses: actions/checkout@v3

      - name: get version
        id: app_version
        run: echo "new_version=`cat pubspec.yaml | grep -o 'version:[^:]*' | cut -f2 -d":" | cut -d"+" -f1 | xargs`" >> "$GITHUB_OUTPUT"

  build_android_test:
    name: Android-test
    needs: [details]
    uses: ./.github/workflows/build-test.yaml
    with:
      version: "${{needs.details.outputs.new_version}}-branch-name"
    secrets:
      KEY_PROPERTIES: ${{secrets.KEY_PROPERTIES}}
      SA_FIREBASE: ${{secrets.SA_FIREBASE}}
      FIREBASE_APP_ID_ANDROID: ${{secrets.FIREBASE_APP_ID_ANDROID}}
      FIREBASE_OPTIONS: ${{secrets.FIREBASE_OPTIONS}}
